### ISSUE TITLE
lateinit property fragmentDispatchingAndroidInjector has not been initialized

### ISSUE THREAD

**Issue by hengkyz** [MindorksOpenSource/android-kotlin-mvp-architecture#11]
lateinit property fragmentDispatchingAndroidInjector has not been initialized

when we open feed menu then try to change the display orientation it will show that error

**Comment by padhur** [comment]
Is this issue fixed?

**Comment by Sarohy** [comment]
Anyone find the solution to it ??

**Comment by amitshekhariitbhu** [comment]
@hengkyz @padhur @Sarohy I just pushed the fix.
