### ISSUE TITLE
Adding a new activity

### ISSUE THREAD

**Issue by HassanRazaCrewLogix** [MindorksOpenSource/android-kotlin-mvp-architecture#28]
I am trying to add a new activity it is giving me  error on this please help !
`
@Module
class SignupActivityModule {
    @Provides
    internal fun provideSignupInteractor(interactor: SignupInteractor): SignupMVPInteractor = interactor

    @Provides
    internal fun provideSignupPresenter(presenter: SignupPresenter<SignupMVPView,SignupMVPInteractor>)
            : SignupMVPPresenter<SignupMVPView, SignupMVPInteractor> = presenter
}`
`interface SignupMVPView : MVPView {
    fun showValidationMessage(errorCode: Int)
    fun openMainActivity()
    fun showResponseToast(response:String)
}`
`class SignupActivity : BaseActivity(), SignupMVPView {
    @Inject
    internal lateinit var presenter: SignupMVPPresenter<SignupMVPView, SignupMVPInteractor>
    override fun showResponseToast(response: String) {
        toast(message = response)
    }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_signup)
        presenter.onAttach(this)
    }
    override fun onDestroy() {
        presenter.onDetach()
        super.onDestroy()
    }
    override fun showValidationMessage(errorCode: Int) {
    }
    override fun openMainActivity() {
        val intent = Intent(this, MainActivity::class.java)
        startActivity(intent)
        finish()
    }
    override fun onFragmentAttached() {
    }
    override fun onFragmentDetached(tag: String) {
    }
    fun toast(message: CharSequence) =
            Toast.makeText(this@SignupActivity, message, Toast.LENGTH_SHORT).show()
}`
`class SignupPresenter<V : SignupMVPView, I : SignupMVPInteractor> @Inject internal constructor(interactor: I, schedulerProvider: SchedulerProvider, disposable: CompositeDisposable) : BasePresenter<V, I>(interactor = interactor, schedulerProvider = schedulerProvider, compositeDisposable = disposable), SignupMVPPresenter<V, I> {
    override fun onServerSignupClicked(username: String, password: String, confirmPassword: String, fullName: String, phone: String, role: String) {
        when {
            username.isEmpty() -> getView()?.showValidationMessage(AppConstants.EMPTY_EMAIL_ERROR)
            password.isEmpty() -> getView()?.showValidationMessage(AppConstants.EMPTY_PASSWORD_ERROR)
            else -> {
                getView()?.showProgress()
                interactor?.let {
                    compositeDisposable.add(it.doServerSignupApiCall(username, password, confirmPassword, fullName, phone, role)
                            .compose(schedulerProvider.ioToMainObservableScheduler())
                            .subscribe({ loginResponse ->
               getView()?.showResponseToast(loginResponse.message!!)
           }, { err -> println(err) }))
                }}}}}`
`interface SignupMVPPresenter<V : SignupMVPView, I : SignupMVPInteractor> : MVPPresenter<V, I> {
    fun onServerSignupClicked(username: String, password: String, confirmPassword: String, fullName: String, phone: String, role: String)
}`
`interface SignupMVPInteractor : MVPInteractor {
    fun doServerSignupApiCall(username: String, password: String, confirmPassword: String, fullName: String, phone: String, role: String): Observable<SignupResponse>
}`
`class SignupInteractor @Inject internal constructor(preferenceHelper: PreferenceHelper, apiHelper: ApiHelper) : BaseInteractor(preferenceHelper, apiHelper), SignupMVPInteractor {
    override fun doServerSignupApiCall(username: String, password: String,
                                       confirmPassword: String, fullName: String,
                                       phone: String, role: String) =
            apiHelper.performServerSignup(SignupRequest.ServerSignupRequest(username = username,
                    password = password, confirPassword = confirmPassword, fullName = fullName,
                    phone = phone, role = role))

}`

I am following same as login but getting error in activity builder

`@Module
abstract class ActivityBuilder {

    @ContributesAndroidInjector(modules = [(SplashActivityModule::class)])
    abstract fun bindSplashActivity(): SplashMVPActivity

    @ContributesAndroidInjector(modules = [(SignupActivity::class)])
    abstract fun bindSignupActivity(): SignupActivity

    @ContributesAndroidInjector(modules = [(MainActivityModule::class), (RateUsDialogFragmentProvider::class), (AboutFragmentProvider::class)])
    abstract fun bindMainActivity(): MainActivity

    @ContributesAndroidInjector(modules = [(LoginActivityModule::class)])
    abstract fun bindLoginActivity(): LoginActivity

    @ContributesAndroidInjector(modules = [(BlogFragmentProvider::class), (OpenSourceFragmentProvider::class)])
    abstract fun bindFeedActivity(): FeedActivity}`

I am getting this error
di\builder\ActivityBuilder.java:17: error: .ui.signup.view.SignupActivity is not a @Module
    @dagger.android.ContributesAndroidInjector(modules = {.ui.signup.view.SignupActivity.class})
    ^
![5issue](https://user-images.githubusercontent.com/48272946/54350771-dfb4e800-466f-11e9-85ca-a2eb4f517254.PNG)
![6issue](https://user-images.githubusercontent.com/48272946/54350772-e04d7e80-466f-11e9-919e-a0ac4950eb6d.PNG)
![7issue](https://user-images.githubusercontent.com/48272946/54350774-e04d7e80-466f-11e9-8615-0d75713fb231.PNG)
![8issue](https://user-images.githubusercontent.com/48272946/54350775-e04d7e80-466f-11e9-9032-a2fdf1d777f5.PNG)
![1issue](https://user-images.githubusercontent.com/48272946/54350776-e0e61500-466f-11e9-9a1a-71c7b3d91f49.PNG)
![2issue](https://user-images.githubusercontent.com/48272946/54350778-e0e61500-466f-11e9-90c4-deb1a71fccc6.PNG)
![3issue](https://user-images.githubusercontent.com/48272946/54350780-e0e61500-466f-11e9-80d8-75b2de81e6a1.PNG)
![4issue](https://user-images.githubusercontent.com/48272946/54350781-e17eab80-466f-11e9-8524-f332d2918d88.PNG)
code is  in png images also

**Comment by anandgaurav10** [comment]
@ContributesAndroidInjector(modules = [(SignupActivityModule::class)])
abstract fun bindSignupActivity(): SignupActivity

Check module
